config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'users#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'boards#search'
  get 'mypage', to: 'users#mypage'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  resources :sessions
  namespace :admin do
    resources :users
  end

  resources :boards do
    post 'add', to: 'favorites#create'
    delete 'add', to: 'favorites#destroy'
  end
  resources :comments, only: %i[create destroy]
  resources :favorites, only: %i[index]
  resources :questions
  resources :answers, only: %i[create destroy]
  resources :homes
  resources :conversations do
    resources :messages
  end
  resources :users
end

app/models/favorite.rb
# == Schema Information
#
# Table name: favorites
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  board_id   :bigint           not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_favorites_on_board_id              (board_id)
#  index_favorites_on_user_id               (user_id)
#  index_favorites_on_user_id_and_board_id  (user_id,board_id) UNIQUE
#

class Favorite < ApplicationRecord
  default_scope -> { order(updated_at: :desc) }
  belongs_to :user
  belongs_to :board, counter_cache: :favorites_count
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :current_user
  before_action :authenticate_user, only: %i[index]

  def index
    @favorites = @current_user.favorites.page(params[:page])
  end

  def create
    user = current_user
    @board = Board.find(params[:board_id])
    if Favorite.create(user_id: user.id, board_id: @board.id)
    else
      flash[:notice] = '登録できませんでした。'
      redirect_to boards_path
    end
  end

  def destroy
    user = current_user
    @board = Board.find(params[:board_id])
    favorite = Favorite.find_by(user_id: user.id, board_id: @board.id)
    if favorite.destroy
    else
      flash[:notice] = 'お気に入り解除できませんでした。'
      redirect_to boards_path

    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% favorite = @current_user.favorites.find_by(board_id: board.id) %>
<% if favorite.present? %>
  <%= link_to 'お気に入りをはずす',board_add_path(board), method: :delete, id: "favorite-button", remote: true, class: "fas fa-heart"%>
<% else %>
  </i><%= link_to 'お気に入り！', board_add_path(board), method: :post, id: "favorite-button", remote: true, class: "far fa-heart" %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_btn_<%= @board.id %>").html("<%= j(render partial: "favorites/favorite", locals: {board: @board})%>");

app/views/favorites/destroy.js.erb
$("#favorite_btn_<%= @board.id %>").html("<%= j(render partial: "favorites/favorite", locals: {board: @board})%>");

app/views/favorites/index.html.erb
<div class="favorite_index">
  <% @favorites.each do |favorite| %>
  <ul class="list-group">
    <li class="list-group-item">
      <div class="board_user">
        <div class="board_user_image">
          <% if favorite.board.user.image.attached? %>
            <%=link_to image_tag(favorite.board.user.image,height:55), favorite.board.user %>
          <% else %>
            <%= link_to image_tag('human.jpeg', width: 40), favorite.board.user %>
          <% end %>
        </div>
        <div class= 'board_user_name'>
          <%= favorite.board.user.name %>
        </div>
      </div>
      <div class="board_title">
        <%= favorite.board.title %><br>
        <p class="board_update">
          <%= favorite.board.updated_at.to_s(:datetime_jp)%>
        </p>
      </div>
      <div class="board_tag">
        <% favorite.board.tags.each do |tag| %>
          <span class ="badge badge-success"><%= tag.name %></span>
        <% end %>
      </div>
    </li>
    <li class="list-group-item">
      <div class="board_body">
        <p class="card-text">
          <%= simple_format(favorite.board.body) %>
        </p>
        <p class="card-left"></p>
        <% if favorite.board.images.attached? %>
          <% favorite.board.images.each do |image| %>
            <div class="board_up_image">
              <%= image_tag(image,width:400) %>
            </div>
          <% end %>
        <% end %>
      </div>
    </li>
    <li class="list-group-item">
      <%= link_to 'コメントする', board_path(favorite.board)%>
    </li>
  </ul><br>
  <% end %>
</div>
<%= paginate @favorites %>