config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'users#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'boards#search'
  get 'mypage', to: 'users#mypage'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  resources :sessions
  namespace :admin do
    resources :users
  end

  resources :boards do
    post 'add', to: 'favorites#create'
    delete 'add', to: 'favorites#destroy'
  end
  resources :comments, only: %i[create destroy]
  resources :favorites, only: %i[index]
  resources :questions
  resources :answers, only: %i[create destroy]
  resources :homes
  resources :conversations do
    resources :messages
  end
  resources :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  admin                  :boolean          default(FALSE), not null
#  age                    :integer
#  country_you_want_to_go :string(255)
#  email                  :string(255)      not null
#  favorite_country       :string(255)
#  introduction           :text(65535)
#  name                   :string(255)      not null
#  password_digest        :string(255)      not null
#  sex                    :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  has_one_attached :image, dependent: :delete_all
  has_secure_password
  has_many :boards, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :fav_boards, through: :favorites, source: :board
  has_many :questions, dependent: :delete_all
  has_many :answers, dependent: :delete_all

  validates :name,
    presence: true,
    uniqueness: true,
    length: {maximum: 16}

  validates :email,
    presence: true,
    uniqueness: true,
    length: {maximum: 50}

  validates :password,
    length: {minimum: 8}

  enum sex: { 男: 0, 女: 1}

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def new
    @user = User.new
  end

  def create
    user = User.new(admin_user_params)
    if user.save
      redirect_to admin_users_path
    else
      redirect_to admin_new_users_path, flash:{
        user: user,
        error_messages: user.errors.full_messages
      }
    end

  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def admin_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def admin_user
    redirect_to (user_path(@current_user)) unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: %i[show edit index]
  before_action :authenticate_user, only: %i[edit show]
  before_action :collect_user, only: %i[edit]

  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "『#{user.name}』さんのユーザー登録が完了しました！！"
      redirect_to boards_path
    else
      redirect_back fallback_location: new_user_path, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end
  end

  def index
    @user = @current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "「#{@user.name}」の情報が修正されました。"
      redirect_to user_path(@user)
    else
      redirect_back fallback_location: edit_user_path, flash: {
        user: @user,
        error_messages: @user.errors.full_messages
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :age, :sex, :favorite_country, :country_you_want_to_go, :introduction, :admin)
  end

  def collect_user
    if @current_user.id != params[:id].to_i
    flash[:notice] = "あなたには権限がありません。"
    redirect_to user_path(@current_user)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render 'shared/error_messages' %>
<%= form_with model: user do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード(8文字以上)' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit '新規作成', class: 'btn btn-outline-secondary' %>
  <div class="signin_back_button">
    <%= link_to '戻る', root_path, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/users/_login_form.html.erb
<h3 class= 'login_page_word'>ログイン</h3>
<% if flash[:notice] %>
  <div class="alert alert-danger" >
    <%= flash[:notice] %>
  </div>
<% end %>
<%= form_with scope: :session, url: login_path do |f| %>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <%= f.submit 'ログイン', class: 'btn btn-outline-secondary' %>
  <div class="login_back_button">
    <%= link_to '戻る', root_path, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h2>プロフィールの編集</h2>
<%= render 'shared/error_messages'%>
<%= form_with model: @user do |f| %>
  <div class="form-group">
    <% if @current_user.image.attached? %>
      <%= f.label :image, 'ユーザー画像' %><br>
    <% end %>
    <%= image_tag @current_user.image.variant(auto_orient: true),width:200 if @current_user.image.attached? %><br><br>
    <%= f.label :image, '画像を変更する' %><br>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード（８文字以上）' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認用）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="form-group__age">
    <%= f.label :age, '年齢' %>
    <%= f.number_field :age, in: 1...121 , class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :sex, '性別' %><br>
    <%= f.label :男 %>
   <%= f.radio_button :sex, :男 %>
   <%= f.label :女 %>
   <%= f.radio_button :sex, :女 %>
  </div>
  <div class="form-group">
    <%= f.label :favorite_country, '好きな国（場所）' %>
    <%= f.text_field :favorite_country, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :country_you_want_to_go, '行ってみたい国（場所）' %>
    <%= f.text_field :country_you_want_to_go, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :introduction, '自己紹介' %>
    <%= f.text_area :introduction, class: 'form-control', rows: 10%>
  </div>
  <%= f.submit '編集', class: 'btn btn-primary' %>
<% end %>

app/views/users/index.html.erb
<h3>ユーザー一覧</h3>
<% @users.each do |user| %>
  <% if user.id != @current_user.id %>
    <ul class="list-group">
      <li class="list-group-item">
        <div class="users_image">
          <% if user.image.attached? %>
            <%= image_tag(user.image,height:55)%>
          <% else %>
            <%= image_tag 'human.jpeg', width: 50 %>
          <% end %>
        </div>
        <div class="users_name">
          <%= link_to user.name, user %>
        </div>
        <div class="users_message">
          <%= link_to 'メッセージする', conversations_path(sender_id: @current_user.id, recipient_id: user.id), method: :post, class:'btn btn-outline-success'%>
        </div>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/users/login.html.erb
<%= render partial: 'users/login_form' %>

app/views/users/new.html.erb
<h3 class = 'signin_page_word'>ユーザー登録</h3>
<%= render partial: 'form', locals: { user: @user } %>

app/views/users/show.html.erb
<div class="profile_error">
</div>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if @current_user == @user %>
  <div class="edit_profile_link">
    <%= link_to 'プロフィールを編集する', edit_user_path(@user.id), class:'btn btn-outline-success'%>
  </div>
<% else %>
  <div class="edit_profile_link">
    <%= link_to 'メッセージする', conversations_path(sender_id: @current_user.id, recipient_id: @user.id), method: :post, class:'btn btn-outline-success' %>
  </div>
<% end %>
<div class="profile_image">
  <% if @user.image.attached? %>
    <%= image_tag(@user.image,width:200) %>
  <% else %>
    <%= image_tag 'human.jpeg', width:160 %>
  <% end %>
</div>
<ul class="list-group profile_flame2">
  <li class="list-group-item">
    名前 : <%= @user.name %>
  </li>
  <li class="list-group-item">
    年齢 :  <%= @user.age %>　　　
    性別 :  <%= @user.sex %>
  </li>
  <li class="list-group-item">
    好きな国（場所）: <%= @user.favorite_country %>
  </li>
  <li class="list-group-item">
    行きたい国（場所）: <%= @user.country_you_want_to_go %>
  </li>
  <li class="list-group-item">
    自己紹介 : <%= @user.introduction %>
  </li>
</ul>
<% if @current_user.admin == true %>
  <div class="admin_user_link">
    <%= link_to 'ユーザー管理画面', admin_users_path, class:'btn btn-outline-danger'%> : <%= @current_user.name %>は全てのユーザーを管理する権限があります
  </div>
<% end %>
<br><br><br>
<div class="user_boards">
  最近の投稿
</div>
<hr style="width:700px; background-color:#888888;">
<br><br>
<% @user.boards.each do |board| %>
  <ul class="list-group">
    <li class="list-group-item">
      <div class="board_user">
        <div class="board_user_image">
          <% if board.user.image.attached? %>
            <%= image_tag(board.user.image,height:55)%>
          <% else %>
            <%= image_tag 'human.jpeg', width: 50 %>
          <% end %>
        </div>
        <div class= 'board_user_name'>
          <%= board.user.name %>
        </div>
      </div>
      <div class="board_title">
        <%= board.title %><br>
        <p class="board_update">
          <%= board.updated_at.to_s(:datetime_jp)%>
        </p>
      </div>
      <div class="board_tag">
        <% board.tags.each do |tag| %>
          <span class ="badge badge-success"><%= tag.name %></span>
        <% end %>
      </div>
    </li>
    <li class="list-group-item">
      <div class="board_body">
        <p class="card-text"><%= simple_format(board.body) %></p>
        <p class="card-left"></p>
        <% if board.images.attached? %>
          <% board.images.each do |image| %>
            <div class="board_up_image">
              <%= image_tag(image,width:400) %>
            </div>
          <% end %>
        <% end %>
      </div>
    </li>
    <li class="list-group-item">
      <%= link_to 'コメントする', board_path(board), class:"far fa-comment"%>
      <div class="board_button">
        <%= link_to '詳細', board, class: 'btn btn-outline-dark btn-sm' %>
        <%= link_to '編集', edit_board_path(board), class: 'btn btn-outline-dark btn-sm' %>
        <%= link_to '削除', board, class: 'btn btn-outline-dark btn-sm', method: :delete %>
      </div>
    </li>
  </ul><br>
<% end %>