config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'users#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'boards#search'
  get 'mypage', to: 'users#mypage'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  resources :sessions
  namespace :admin do
    resources :users
  end

  resources :boards do
    post 'add', to: 'favorites#create'
    delete 'add', to: 'favorites#destroy'
  end
  resources :comments, only: %i[create destroy]
  resources :favorites, only: %i[index]
  resources :questions
  resources :answers, only: %i[create destroy]
  resources :homes
  resources :conversations do
    resources :messages
  end
  resources :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  admin                  :boolean          default(FALSE), not null
#  age                    :integer
#  country_you_want_to_go :string(255)
#  email                  :string(255)      not null
#  favorite_country       :string(255)
#  introduction           :text(65535)
#  name                   :string(255)      not null
#  password_digest        :string(255)      not null
#  sex                    :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  has_one_attached :image, dependent: :delete_all
  has_secure_password
  has_many :boards, dependent: :delete_all
  has_many :comments, dependent: :delete_all
  has_many :favorites, dependent: :delete_all
  has_many :fav_boards, through: :favorites, source: :board
  has_many :questions, dependent: :delete_all
  has_many :answers, dependent: :delete_all

  validates :name,
    presence: true,
    uniqueness: true,
    length: {maximum: 16}

  validates :email,
    presence: true,
    uniqueness: true,
    length: {maximum: 50}

  validates :password,
    length: {minimum: 8}

  enum sex: { 男: 0, 女: 1}

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_user

  def new
    @user = User.new
  end

  def create
    user = User.new(admin_user_params)
    if user.save
      redirect_to admin_users_path
    else
      redirect_to admin_new_users_path, flash:{
        user: user,
        error_messages: user.errors.full_messages
      }
    end

  end

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def admin_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def admin_user
    redirect_to (user_path(@current_user)) unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: %i[show edit index]
  before_action :authenticate_user, only: %i[edit show]
  before_action :collect_user, only: %i[edit]

  def new
    @user = User.new(flash[:user])
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "『#{user.name}』さんのユーザー登録が完了しました！！"
      redirect_to boards_path
    else
      redirect_back fallback_location: new_user_path, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end
  end

  def index
    @user = @current_user
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "「#{@user.name}」の情報が修正されました。"
      redirect_to user_path(@user)
    else
      redirect_back fallback_location: edit_user_path, flash: {
        user: @user,
        error_messages: @user.errors.full_messages
      }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :age, :sex, :favorite_country, :country_you_want_to_go, :introduction, :admin)
  end

  def collect_user
    if @current_user.id != params[:id].to_i
    flash[:notice] = "あなたには権限がありません。"
    redirect_to user_path(@current_user)
    end
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h2>ユーザー管理画面</h2>
<%= link_to '新規ユーザー作成', new_admin_user_path, class:'btn btn-outline-success' %>
<% @users.each do |user| %>
  <ul class="list-group">
    <li class="list-group-item">
      <div class="admin_users_name">
        <%= link_to user.name, user %>
      </div>
      <div class="admin_users_message">
        <%= link_to 'メッセージ', conversations_path(sender_id: @current_user.id, recipient_id: user.id), method: :post %>
      </div>
      <div class="admin_users_delete">
        <%= link_to '削除', admin_user_path(user), method: :delete, data: {confirm: '削除してよろしいですか？'} %>
      </div>
      <div class="admin_users_admin">
        管理者権限　：　<%= user.admin %>
      </div>
    </li>
  </ul>
<% end %>

app/views/admin/users/new.html.erb
<%= render 'shared/error_messages' %>
<%= form_with model: [:admin, @user], local: true do |f| %>
  <div class="form-group">
    <%= f.label :name, 'ユーザー名' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password, 'パスワード(8文字以上)' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation, 'パスワード（確認）' %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <div class="form-group">
     <%= f.check_box :admin %>
     <%= label_tag :admin, '管理者権限'%>
  </div>
  <%= f.submit '新規作成', class: 'btn btn-outline-secondary' %>
<% end %>