config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'users#login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'search', to: 'boards#search'
  get 'mypage', to: 'users#mypage'
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#index'
  resources :sessions
  namespace :admin do
    resources :users
  end

  resources :boards do
    post 'add', to: 'favorites#create'
    delete 'add', to: 'favorites#destroy'
  end
  resources :comments, only: %i[create destroy]
  resources :favorites, only: %i[index]
  resources :questions
  resources :answers, only: %i[create destroy]
  resources :homes
  resources :conversations do
    resources :messages
  end
  resources :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user
    if @current_user == nil
      flash[:notice] = 'ログインしてください'
      redirect_to login_path
    else
    end
  end

  def current_user
    return unless session[:user_id]
    @current_user = User.find_by(id: session[:user_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def header_link_item(name, path)
    class_name = 'nav-item'
    class_name << 'active' if current_page?(path)

    content_tag :li, class: class_name do
      link_to name, path, class: 'nav-link'
    end
  end
end

app/views/application/_header.html.erb
<div class="header_all">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">BACK PACKER's note</a>
  <% if @current_user %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          ユーザー
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'マイページ', user_path(@current_user), class: 'dropdown-item' %>
          <%= link_to 'ユーザー一覧', users_path, class: 'dropdown-item' %>
          <%= link_to 'ログアウト', logout_path, method: :delete, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          情報ノート
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'ノート一覧', boards_path , class: 'dropdown-item' %>
            <%= link_to '新規ノート作成', new_board_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          質問箱
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to '質問一覧', questions_path , class: 'dropdown-item' %>
            <%= link_to '質問作成', new_question_path, class: 'dropdown-item' %>
        </div>
      </li>
      <li class="nav-item">
        <%= header_link_item('お気に入り', favorites_path) %>
      </li>
    </ul>
  </div>
  <% else %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= header_link_item('ログイン', login_path) %>
    </li>
    <li class="nav-item">
      <%= header_link_item('新規登録', new_user_path) %>
    </li>
  </ul>
  </div>
  <% end %>
</nav>
</div>